// <auto-generated />
using System;
using Blog.Services.PostsAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blog.Services.PostsAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230318010046_AddUserNameInContext")]
    partial class AddUserNameInContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-rc.1.22426.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blog.Services.PostsAPI.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            CreatedDate = new DateTime(2023, 3, 18, 4, 0, 45, 955, DateTimeKind.Local).AddTicks(1862),
                            Name = "Тестовый пост 1",
                            Text = "...",
                            UserName = "TestUser"
                        },
                        new
                        {
                            PostId = 2,
                            CreatedDate = new DateTime(2023, 3, 18, 4, 0, 45, 955, DateTimeKind.Local).AddTicks(1898),
                            Name = "Тестовый пост 2",
                            Text = "...",
                            UserName = "TestUser"
                        },
                        new
                        {
                            PostId = 3,
                            CreatedDate = new DateTime(2023, 3, 18, 4, 0, 45, 955, DateTimeKind.Local).AddTicks(1906),
                            Name = "Тестовый пост 3",
                            Text = "...",
                            UserName = "TestUser"
                        },
                        new
                        {
                            PostId = 4,
                            CreatedDate = new DateTime(2023, 3, 18, 4, 0, 45, 955, DateTimeKind.Local).AddTicks(1956),
                            Name = "Тестовый пост 4",
                            Text = "...",
                            UserName = "TestUser"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
